# build stage
FROM docker.io/node:lts-alpine3.23 as build-stage

WORKDIR /app

COPY package*.json ./
RUN npm install

COPY . .

RUN npm run build

# production stage
FROM docker.io/nginx:stable-alpine3.23-slim as production-stage

COPY --from=build-stage /app/dist /usr/share/nginx/html

# Replace the default NGINX configuration
COPY default.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]