version: "3.9"
services:
  ether-faucet-frontend:
    container_name: ether-faucet-frontend
    image: ghcr.io/aplonks/ether-faucet-frontend:main
    ports: 
      - 5001:80
    env_file:
      - .env_compose
    networks: 
      - bcnetwork

  ether-faucet-backend:
    container_name: ether-faucet-backend
    image: ghcr.io/aplonks/ether-faucet-backend:main
    ports: 
      - 5002:5002
    env_file:
      - .env_compose
    networks: 
      - bcnetwork

  redis-stack:
    container_name: redis-stack
    image: docker.io/redis/redis-stack:7.2.0-v9
    ports:
      - "8001:8001"
      - "6379:6379"
    networks:
      - bcnetwork

networks:
  bcnetwork:
    name: bcnetwork
    driver: bridge
    external: true

