# Build the application from source
FROM docker.io/golang:1.22 AS build-stage

WORKDIR /app

COPY . .
# COPY go.mod go.sum ./
RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -o build/main-linux-amd64 cmd/main.go

# Run the tests in the container
# FROM build-stage AS run-test-stage
# RUN go test -v ./...

# Deploy the application binary into a lean image
FROM docker.io/alpine:3.19 AS build-release-stage

WORKDIR /

COPY --from=build-stage /app/build/main-linux-amd64 /main-linux-amd64

# COPY CONFIGURATION NGINX FOR RELOAD IN SPA

EXPOSE 8080

ENTRYPOINT ["/main-linux-amd64"]